Presentation/Safari.UI.Web/Areas/Admin/Controllers/PrecioApiController.cs
using Safari.Entities;
using Safari.UI.Process;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Safari.UI.Web.Areas.Admin.Controllers
{
    public class PrecioApiController : Controller
    {
        public ActionResult Index()
        {
            var p = new PrecioApiProcess();
            return View(p.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Precio precio)
        {
            try
            {
                var p = new PrecioApiProcess();
                p.Add(precio);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new PrecioApiProcess();
            Precio precio = p.ReadBy(id.Value);
            if (precio == null)
            {
                return HttpNotFound();
            }
            return View(precio);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new PrecioApiProcess();
            Precio precio = p.ReadBy(id.Value);
            if (precio == null)
            {
                return HttpNotFound();
            }
            return View(precio);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Precio precio)
        {
            if (ModelState.IsValid)
            {
                var p = new PrecioApiProcess();
                p.Update(precio);
                return RedirectToAction("Index");
            }
            return View(precio);
        }



        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new PrecioApiProcess();
            Precio precio = p.ReadBy(id.Value);
            if (precio == null)
            {
                return HttpNotFound();
            }
            return View(precio);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var p = new PrecioApiProcess();

            Precio precio = p.ReadBy(id);
            p.Delete(precio);
            return RedirectToAction("Index");
        }
    }
}

Presentation/Safari.UI.Web/Areas/Admin/Views/PrecioApi/Create.cshtml
@model Safari.Entities.Precio

@{
    ViewBag.Title = "Create";
}
@section head {
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
}
<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Precio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TipoServicioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoServicioId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoServicioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDesde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDesde, new { htmlAttributes = new { @class = "datefield form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDesde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaHasta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHasta, new { htmlAttributes = new { @class = "datefield form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHasta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/datepicker-esAR.js"></script>
}

Presentation/Safari.UI.Web/Areas/Admin/Views/PrecioApi/Delete.cshtml
@model Safari.Entities.Precio

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Precio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoServicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoServicio.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDesde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDesde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaHasta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaHasta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

Presentation/Safari.UI.Web/Areas/Admin/Views/PrecioApi/Details.cshtml
@model Safari.Entities.Precio

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Precio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TipoServicio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoServicio.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaDesde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaDesde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaHasta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaHasta)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) 
</p>

Presentation/Safari.UI.Web/Areas/Admin/Views/PrecioApi/Edit.cshtml
@model Safari.Entities.Precio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}
@section head {
    <link href="~/Content/themes/base/jquery-ui.css" rel="stylesheet" />
}
<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Precio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.TipoServicioId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TipoServicioId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TipoServicioId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaDesde, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaDesde, new { htmlAttributes = new { @class = "datefield form-control" } })
                @Html.ValidationMessageFor(model => model.FechaDesde, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaHasta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaHasta, new { htmlAttributes = new { @class = "datefield form-control" } })
                @Html.ValidationMessageFor(model => model.FechaHasta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script src="~/Scripts/datepicker-esAR.js"></script>
}

Presentation/Safari.UI.Web/Areas/Admin/Views/PrecioApi/Index.cshtml
@model IEnumerable<Safari.Entities.Precio>

@{
                /**/

                ViewBag.Title = "Precio";
}

<h2>Precios</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create", "", new { @class = "btn btn-primary @*btn-sm*@" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TipoServicio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaDesde)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaHasta)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.TipoServicioId)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaDesde)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.FechaHasta)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Valor)
    </td>
    <td>
        @*@Html.ActionLink("Ver", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-xs" })
            @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-xs" })
            @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })*@

        <a class="btn btn-info btn-xs" id="iframe-ver" href="@Url.Action("Details","PrecioApi", new { id = item.Id })">Ver</a>
        <a class="btn btn-warning btn-xs" id="iframe-editar" href="@Url.Action("Edit","PrecioApi", new { id = item.Id })">Editar</a>
        <a class="btn btn-danger btn-xs" id="iframe-eliminar" href="@Url.Action("Delete","Precio", new { id = item.Id })">Eliminar</a>
    </td>
</tr>
}

</table>


@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script src="~/Scripts/fancybox.js"></script>
    <script>

        $(document).ready(function () {
        $("#iframe-ver").fancybox({
            type: 'iframe',
            afterClose: function () { window.location.reload(); },
        });
        });

        $(document).ready(function () {
            $("#iframe-editar").fancybox({
                type: 'iframe',
                afterClose: function () { window.location.reload(); },
            });
        });

        $(document).ready(function () {
            $("#iframe-eliminar").fancybox({
                type: 'iframe',
                afterClose: function () { window.location.reload(); },
            });
        });

    </script>


}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>