Presentation/Safari.UI.Web/Areas/Admin/Controllers/EspecieApiController.cs
using Safari.Entities;
using Safari.UI.Process;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;

namespace Safari.UI.Web.Areas.Admin.Controllers
{
    public class EspecieApiController : Controller
    {
        // GET: Admin/EspecieApi
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            var p = new EspecieApiProcess();
            var lista = p.ToList();

            ViewBag.CurrentSort = sortOrder;

            ViewBag.NameSortParm = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var especie = from s in lista select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                especie = especie.Where(s => s.Nombre.Contains(searchString));
            }


            switch (sortOrder)
            {
                case "name_desc":
                    especie = especie.OrderByDescending(s => s.Nombre);
                    break;
                default:
                    especie = especie.OrderBy(s => s.Nombre);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(especie.ToPagedList(pageNumber, pageSize));
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(Especie especie)
        {
            try
            {
                var p = new EspecieApiProcess();
                p.Add(especie);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new EspecieApiProcess();
            Especie especie = p.ReadBy(id.Value);
            if (especie == null)
            {
                return HttpNotFound();
            }
            return View(especie);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new EspecieApiProcess();
            Especie especie = p.ReadBy(id.Value);
            if (especie == null)
            {
                return HttpNotFound();
            }
            return View(especie);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nombre")] Especie especie)
        {
            if (ModelState.IsValid)
            {
                var p = new EspecieApiProcess();
                p.Update(especie);
                return RedirectToAction("Index");
            }
            return View(especie);
        }



        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new EspecieApiProcess();
            Especie especie = p.ReadBy(id.Value);
            if (especie == null)
            {
                return HttpNotFound();
            }
            return View(especie);
        }

        // POST: Especie/Delete/5
        [HttpPost]
        public ActionResult Delete(Especie especie)
        {
            var p = new EspecieApiProcess();
            
            //Especie especie = p.ReadBy(id);
            p.Delete(especie);
            return RedirectToAction("Index");
        }


    }
}

Presentation/Safari.UI.Web/Areas/Admin/Views/EspecieApi/Create.cshtml
@model Safari.Entities.Especie

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Especie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentation/Safari.UI.Web/Areas/Admin/Views/EspecieApi/Delete.cshtml
@model Safari.Entities.Especie

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Especie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

Presentation/Safari.UI.Web/Areas/Admin/Views/EspecieApi/Details.cshtml
@model Safari.Entities.Especie

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Especie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) 
</p>

Presentation/Safari.UI.Web/Areas/Admin/Views/EspecieApi/Edit.cshtml
@model Safari.Entities.Especie

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Especie</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentation/Safari.UI.Web/Areas/Admin/Views/EspecieApi/Index.cshtml
@model PagedList.IPagedList<Safari.Entities.Especie>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@{
    ViewBag.Title = "Especie";
}

<h2>Especie</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create", "", new { @class = "btn btn-primary @*btn-sm*@" })
</p>

@using (Html.BeginForm("Index", "EspecieApi", FormMethod.Get))
{
    <p>
        Find: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Search" new { class="btn btn-primary btn-sm" } />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Nombre", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @*@Html.ActionLink("Ver", "Details", new { id = item.Id }, new { @class = "btn btn-info btn-xs" })
                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }, new { @class = "btn btn-warning btn-xs" })
                    @Html.ActionLink("Eliminar", "Delete", new { id = item.Id }, new { @class = "btn btn-danger btn-xs" })*@

                <a class="btn btn-info btn-xs" id="iframe-ver" href="@Url.Action("Details","EspecieApi", new { id = item.Id })">Ver</a>
                <a class="btn btn-warning btn-xs" id="iframe-editar" href="@Url.Action("Edit","EspecieApi", new { id = item.Id })">Editar</a>
                <a class="btn btn-danger btn-xs" id="iframe-eliminar" href="@Url.Action("Delete","EspecieApi", new { id = item.Id })">Eliminar</a>
            </td>
        </tr>
    }

</table>



Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))



@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script src="~/Scripts/fancybox.js"></script>
    <script>

        $(document).ready(function () {
        $("#iframe-ver").fancybox({
            type: 'iframe',
            afterClose: function () { window.location.reload(); },
        });
        });

        $(document).ready(function () {
            $("#iframe-editar").fancybox({
                type: 'iframe',
                afterClose: function () { window.location.reload(); },
            });
        });

        $(document).ready(function () {
            $("#iframe-eliminar").fancybox({
                type: 'iframe',
                afterClose: function () { window.location.reload(); },
            });
        });

    </script>


}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>