Presentation/Safari.UI.Web/Areas/Admin/Controllers/TipoMovimientoApiController.cs
using Safari.Entities;
using Safari.UI.Process;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Safari.UI.Web.Areas.Admin.Controllers
{
    public class TipoMovimientoApiController : Controller
    {
        public ActionResult Index()
        {
            var p = new TipoMovimientoApiProcess();
            return View(p.ToList());
        }


        public ActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Create(TipoMovimiento tipoMovimiento)
        {
            try
            {
                var p = new TipoMovimientoApiProcess();
                p.Add(tipoMovimiento);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new TipoMovimientoApiProcess();
            TipoMovimiento tipoMovimiento = p.ReadBy(id.Value);
            if (tipoMovimiento == null)
            {
                return HttpNotFound();
            }
            return View(tipoMovimiento);
        }


        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new TipoMovimientoApiProcess();
            TipoMovimiento tipoMovimiento = p.ReadBy(id.Value);
            if (tipoMovimiento == null)
            {
                return HttpNotFound();
            }
            return View(tipoMovimiento);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(TipoMovimiento tipoMovimiento)
        {
            if (ModelState.IsValid)
            {
                var p = new TipoMovimientoApiProcess();
                p.Update(tipoMovimiento);
                return RedirectToAction("Index");
            }
            return View(tipoMovimiento);
        }



        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var p = new TipoMovimientoApiProcess();
            TipoMovimiento tipoMovimiento = p.ReadBy(id.Value);
            if (tipoMovimiento == null)
            {
                return HttpNotFound();
            }
            return View(tipoMovimiento);
        }

        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var p = new TipoMovimientoApiProcess();

            TipoMovimiento tipoMovimiento = p.ReadBy(id);
            p.Delete(tipoMovimiento);
            return RedirectToAction("Index");
        }
    }
}

Presentation/Safari.UI.Web/Areas/Admin/Views/TipoMovimientoApi/Create.cshtml
@model Safari.Entities.TipoMovimiento

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoMovimiento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multiplicador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Multiplicador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Multiplicador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentation/Safari.UI.Web/Areas/Admin/Views/TipoMovimientoApi/Delete.cshtml
@model Safari.Entities.TipoMovimiento

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TipoMovimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Multiplicador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Multiplicador)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> 
        </div>
    }
</div>

Presentation/Safari.UI.Web/Areas/Admin/Views/TipoMovimientoApi/Details.cshtml
@model Safari.Entities.TipoMovimiento

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Details</h2>

<div>
    <h4>TipoMovimiento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Multiplicador)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Multiplicador)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) 
</p>

Presentation/Safari.UI.Web/Areas/Admin/Views/TipoMovimientoApi/Edit.cshtml
@model Safari.Entities.TipoMovimiento

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Funcy.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TipoMovimiento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Multiplicador, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Multiplicador, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Multiplicador, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Presentation/Safari.UI.Web/Areas/Admin/Views/TipoMovimientoApi/Index.cshtml
@model IEnumerable<Safari.Entities.TipoMovimiento>

@{
                /**/

                ViewBag.Title = "TipoMovimiento";
                Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h2>TipoMovimiento</h2>

<p>
    @Html.ActionLink("Crear Nuevo", "Create", "", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Multiplicador)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.Nombre)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Multiplicador)
    </td>
    <td>
        @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })*@

        <a class="btn btn-info btn-xs" id="iframe-ver" href="@Url.Action("Details","TipoMovimientoApi", new { id = item.Id })">Ver</a>
        <a class="btn btn-warning btn-xs" id="iframe-editar" href="@Url.Action("Edit","TipoMovimientoApi", new { id = item.Id })">Editar</a>
        <a class="btn btn-danger btn-xs" id="iframe-eliminar" href="@Url.Action("Delete","TipoMovimiento", new { id = item.Id })">Eliminar</a>
    </td>
</tr>
}

</table>


@section Scripts{
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
    <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>
    <script src="~/Scripts/fancybox.js"></script>
    <script>

        $(document).ready(function () {
        $("#iframe-ver").fancybox({
            type: 'iframe',
            afterClose: function () { window.location.reload(); },
        });
        });

        $(document).ready(function () {
            $("#iframe-editar").fancybox({
                type: 'iframe',
                afterClose: function () { window.location.reload(); },
            });
        });

        $(document).ready(function () {
            $("#iframe-eliminar").fancybox({
                type: 'iframe',
                afterClose: function () { window.location.reload(); },
            });
        });

    </script>


}

<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>

<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css" />
<script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"></script>